# Generated by Django 5.0.7 on 2024-07-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('stock_balance', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
